"""add nullable for review text

Revision ID: 49e8297dc68b
Revises: 93a5c784cfc2
Create Date: 2026-05-14 15:16:58.176744

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "49e8297dc68b"
down_revision: Union[str, Sequence[str], None] = "93a5c784cfc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("responds_order_id_fkey"), "responds", type_="foreignkey")
    op.create_foreign_key(
        None, "responds", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("reviews_order_id_fkey"), "reviews", type_="foreignkey")
    op.create_foreign_key(
        None, "reviews", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")# type: ignore
    op.create_foreign_key(
        op.f("reviews_order_id_fkey"), "reviews", "orders", ["order_id"], ["id"]
    )
    op.drop_constraint(None, "responds", type_="foreignkey")# type: ignore
    op.create_foreign_key(
        op.f("responds_order_id_fkey"), "responds", "orders", ["order_id"], ["id"]
    )
    # ### end Alembic commands ###
