"""add decimal for price

Revision ID: b27032e1b26e
Revises: 975f4f8b8dfa
Create Date: 2026-05-09 15:27:13.808268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b27032e1b26e"
down_revision: Union[str, Sequence[str], None] = "975f4f8b8dfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("deadline_days", sa.Integer(), nullable=False))
    op.add_column("orders", sa.Column("deadline_date", sa.Date(), nullable=True))
    op.drop_column("orders", "deadline")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("deadline", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_column("orders", "deadline_date")
    op.drop_column("orders", "deadline_days")
    # ### end Alembic commands ###
