"""add nullable for review text

Revision ID: c85f8d36dc79
Revises: b27032e1b26e
Create Date: 2026-05-12 19:13:30.308537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c85f8d36dc79"
down_revision: Union[str, Sequence[str], None] = "b27032e1b26e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reviews", "text", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reviews", "text", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
